### ISSUE TITLE
failed to replicate the results

### ISSUE THREAD

**Issue by bingo-todd** [RicherMans/PSL#3]
First, thanks for your work. 

I am trying to replicate the results. Having downloaded the Audioset(resampled to 16k) before, I prepare the hdf5 files as instructed in the code. However, directly running `./train_psl.sh configs/psl_balanced_chunk_10sec.yaml`, the mAP on the eval subset is only 0.01794.
I also tried to run evaluation using pretained teacher model, the mAP on the eval subset is 0.02107. 

About the python environment, I create a new conda environment using the same dependencies except numpy==1.22 and torch_audiomentations==0.11.0 to avoid conflicts (I am using Ubuntu 16.04)

I also found a possible bug in [`src/run.py`](https://github.com/RicherMans/PSL/blob/d07f8e3267b94056e8c683884f709d1144311e30/src/run.py#L357C14-L357C14), the `outputdir` is already included in `saved_params_file`

**Comment by RicherMans** [comment]
Hey,
Can you double check your data once more?
These results are more or less random, so it seems that the data is not correct.

EDIT:
Can you maybe provide me a single soxi on one of the files?

I would be 99% sure from your results that your audio is not standard 16-bit PCM.

Does training even improve any performance?

**Comment by bingo-todd** [comment]
Yes, you are right. 

The audio data I used is encoding with 32-bit Floating Point PCM, however the "[dump_wave_to_hdf5.py](https://github.com/RicherMans/PSL/blob/main/scripts/utils/dump_wave_to_hdf5.py)"  requires int16.
After using the the correct way to load audio files, I can get the same evaluation result using the pretrained model.

Thanks
